# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.8'

services:

  mps-mqutils:
    container_name: 'email_notifier'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    tty: true
    volumes:
      # App
      - './:/home/appuser'
      # Logs
      - './logs:/home/appuser/logs'
    env_file:
      - '.env'
    ports:
      - '10589:8081'